version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
    - DATABASE_URL=postgresql://postgres:postgres@db:5432/pocketfinder
    - JWT_SECRET_KEY=sua-chave-secreta-aqui
    - FLASK_APP=app_factory.py
    - FLASK_ENV=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "rm -rf migrations &&
             flask db init &&
             flask db migrate -m 'Initial migration' &&
             flask db upgrade &&
             flask run --host=0.0.0.0"

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pocketfinder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 